### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by DylanReile** [NoRedInk/rspec-retry#115]
The last commit is from 2019, and there are a number of open issues. Do we need more maintainers?

**Comment by ibalosh** [comment]
seems so based on: https://github.com/NoRedInk/rspec-retry/issues/72

**Comment by michaelglass** [comment]
opened #120, if anyone wants to volunteer to do some maintenance, feel free, and I'll ping folks at NoRedInk to grant access.

**Comment by BrianHicks** [comment]
Hey folks, check #121—hopefully we clarified how we're expecting to maintain this repo in the future. As I mentioned in #120, we'd be happy to link to forks where new development is happening.
