### ISSUE TITLE
set config.default_retry_count = 0 will make tests always passed

### ISSUE THREAD

**Issue by bingxie** [NoRedInk/rspec-retry#17]
When I set config.default_retry_count = 0
it will ignore the binding.pry and always make the tests passed.

**Comment by deepak** [comment]
can we raise an error and fail the build, if `default_retry_count` is zero ?

**Comment by anicholson** [comment]
I think this is related to #11

**Comment by michaelglass** [comment]
if anyone reviews #34, I'll get it merged
