### ISSUE TITLE
How to automatically apply to all specs in a given directory?

### ISSUE THREAD

**Issue by suan** [NoRedInk/rspec-retry#20]
I'd like to transparently apply rspec-retry to all specs in a given directory. Is there an easy way to do that apart from tagging each example individually?

**Comment by karlingen** [comment]
+1

**Comment by fabn** [comment]
:+1:

**Comment by antoniosb** [comment]
:+1:

**Comment by dwbutler** [comment]
I'd like to see something like the following to only retry my feature specs:

```ruby
config.retry_if = ->(example) do
  example.metadata[:type] == :feature
end
```

**Comment by michaelglass** [comment]
haven't tested this but I think it should work
```
RSpec.configure do |config|
  config.before(type: :feature) do |example|
    example.metadata[:retry] = 3
  end
end
```

**Comment by dwbutler** [comment]
@michaelglass Do you think my proposal above - `config.retry_if` - is sensible? I'd love to have a more readable and less hacky way of configuring dynamic retry rules based on example metadata.

**Comment by michaelglass** [comment]
if you PR it, it will come.

**Comment by dwbutler** [comment]
@michaelglass Thanks! I'll put some more thought into what the configuration would look like. I would probably start simple, but the configuration could eventually grow as complicated as Airbrake's. (See https://github.com/airbrake/airbrake/wiki/Customizing-your-airbrake.rb)

If you'd like to add me as a contributor, I would be happy to accept.

**Comment by philipfong** [comment]
I can't seem to get the rspec config to work for me... it still only tries once when I remove the :retry tag from my examples.  Will this feature be merged anytime soon?  It seems very useful to be able to retry all failed tests without having to tag everything.

**Comment by dwbutler** [comment]
@philipfong Feel free to link to the Github branch and try it out. I was waiting for @michaelglass's blessing before merging it.

**Comment by michaelglass** [comment]
sorry I finally got around to it -/
