### ISSUE TITLE
Unclear what the gem is for

### ISSUE THREAD

**Issue by vemv-kantox** [NoRedInk/rspec-retry#37]
Why would I want to retry tests?

**Comment by michaelglass** [comment]
```
RSpec::Retry adds a :retry option for intermittently failing rspec examples. If an example has the :retry option, rspec will retry the example the specified number of times until the example succeeds.
```

Folks shouldn't have intermittently failing tests, but in reality, sometimes those bugs are hard to hunt down and it's much easier to just turn stuff on and off again.  This gem helps stop flakey tests from significantly slowing down progress.

**Comment by michaelglass** [comment]
Could you propose better copy for the readme?

**Comment by vemv-kantox** [comment]
Seems fine to me! I genuinely dind't know why to retry, that was all.
