### ISSUE TITLE
Attaching 'retry: 3' to a specify block does not override the exception list

### ISSUE THREAD

**Issue by CharlesMcMillan** [NoRedInk/rspec-retry#38]
I have a specify block where I specified a retry count:
```ruby
specify 'my test name', retry: 3 do
...
end
```
However, in my config, I have specified
```ruby
config.exceptions_to_retry = [Errno::EPIPE, EOFError]
```
Because I have specified an exception list, the explicit 'retry' on my test doesn't work. The reason I specified 'exceptions_to_retry' is that I globally wanted to retry any/all of my tests if they hit that just that exception; however, in the case that I had a particular test that was flaky, I would like to add a 'retry' param to that test. Am I missing something? Is this already baked in, or is it a feature request?

**Comment by michaelglass** [comment]
to get the functionality you want, you have to also reset `exceptions_to_retry` in your test metadata, e.g.

```
it 'runs a test', retry: 3, exceptions_to_retry: []
  # this should retry 3 times
end
```
it's a little ugly

also: if you want to automatically retry your `config.exceptions_to_retry` exceptions, you have to also change `default_retry_count` to `2`.

best,

-Mike

**Comment by paublyrne** [comment]
Mind if I document this in the README.md ? This was a gotcha for me.
