### ISSUE TITLE
Bad permissions on rspec/retry.rb

### ISSUE THREAD

**Issue by jdelStrother** [NoRedInk/rspec-retry#42]
Hi there - if I install from the gem, all the files in the gem directory have permissions `-rw-r--r--`, with the exception of `lib/rspec/retry.rb`, which is `-rw-------`.   This means that if the gem is installed into a root-owned directory, for example, regular users can't   read that file.

I'm not sure where this problem comes from - if I download the source and run `rake build`, files in the resulting gem have the correct permissions.

**Comment by michaelglass** [comment]
PR and we'll fix it.

**Comment by jdelStrother** [comment]
I'm 95% sure it was just a packaging issue on the 0.4.3 gem - the 0.4.2 gem doesn't have the same problem.  I don't think it's something I can fix via github.

**Comment by michaelglass** [comment]
yah probably my fault.  Will rebuild and push out a small version bump

**Comment by michaelglass** [comment]
can you double check that this is fixed in 0.4.4

**Comment by jdelStrother** [comment]
Yep - looks good, thanks
