### ISSUE TITLE
rspec-retry does not support rspec-2.99.0 or earlier

### ISSUE THREAD

**Issue by hibariya** [NoRedInk/rspec-retry#53]
Since `Procsy` is not a class in this version, rspec-retry doesn't work with rspec-2.99.0. [This branch](https://github.com/NoRedInk/rspec-retry/compare/master...hibariya:rspec-2.x) reproduces that.

To fix the problem, we have to [specify the version](https://github.com/NoRedInk/rspec-retry/compare/master...hibariya:depend-on-rspec3-or-later) of rspec-core 3.0.0 or later. Also rspec-retry-0.4.5 should be yanked.

What do you think?

**Comment by krisleech** [comment]
I just found this out, we have a project using RSpec 2.99, might be worth a note in the README.

**Comment by michaelglass** [comment]
added a note to the readme 352b9b2.

In our appraisals / dependencies, we never supported rspec 2*. Sorry folks!

**Comment by sdhull** [comment]
😢

**Comment by RohanM** [comment]
I encountered this problem also, and was able to solve it by downgrading rspec-retry to 0.4.4. It appears version 0.4.5 and above are incompatible with rspec 2.
