### ISSUE TITLE
rspec-retry-0.5.1 not working with latest rspec-core

### ISSUE THREAD

**Issue by ericcompassion** [NoRedInk/rspec-retry#64]
When trying to run one of my tests, the following error is displayed:

C:/Ruby23/lib/ruby/2.3.0/rubygems/specification.rb:2284:in `raise_if_conflicts': Unable to activate
 rspec-retry-0.5.1, because rspec-core-3.5.3 conflicts with rspec-core (<= 3.5, > 3.3) (Gem::Confli
ctError)

Can you make your version check just be greater than 3.3... I'm guessing that's the problem here,

**Comment by michaelglass** [comment]
resolved in 0.5.2
