### ISSUE TITLE
irb_context warning in rails console

### ISSUE THREAD

**Issue by matthewhively** [NoRedInk/rspec-retry#69]
`irb: warn: can't alias context from irb_context.`
Shows up in rails console if this gem is installed.

rspec gem versions installed (from Gemfile.lock)
`
    rspec-core (3.5.4)
    rspec-expectations (3.5.0)
    rspec-mocks (3.5.0)
    rspec-rails (3.5.2)
    rspec-retry (0.5.3)
    rspec-support (3.5.0)
`

Similar issue in rspec-rails -- not sure if its related though
https://github.com/rspec/rspec-rails/issues/1645

**Comment by michaelglass** [comment]
what version ruby/rails?

**Comment by matthewhively** [comment]
Rails 4.2.7
ruby 2.3.3p222

**Comment by michaelglass** [comment]
unlike `rspec-rails` which needs to be in the development group to load its generators, `rspec-retry` can live safely in your `test` group where it shouldn't interfere with `rails console`

**Comment by jfragoulis** [comment]
Same here.

```
rspec-3.6.0
rspec-rails-3.6.0
rails-5.1.1
ruby 2.3.3
```

It does not happen with rails 4.2.7.1.

**Comment by BrianHicks** [comment]
Auto-closed by PR, sorry. @matthewhively did this solve your problem?

**Comment by matthewhively** [comment]
I would say that is a work around. Since you can choose to run rails console in any environment you choose it doesn't really solve the problem.
Furthermore it seems odd that rspec-retry should require to be placed into a different group from rspec-rails.

However since this has no actual downside of that message in console (that I'm aware of), this work around is good enough I suppose.

NOTE: still occurs in rails 4.2.10
