### ISSUE TITLE
rspec-retry-0.5.5 not working with latest rspec-core (3.7.0)

### ISSUE THREAD

**Issue by ruslanglo** [NoRedInk/rspec-retry#84]
Failure/Error: raise Gem::LoadError, "Unable to activate #{self.full_name}, because #{y}"
Gem::LoadError:
  Unable to activate rspec-retry-0.5.5, because rspec-core-3.7.0 conflicts with rspec-core (< 3.7, > 3.3)

 /usr/share/rubygems/rubygems/specification.rb:2030:in `raise_if_conflicts'
 /usr/share/rubygems/rubygems/specification.rb:1176:in `activate'
 /usr/share/rubygems/rubygems.rb:186:in `rescue in try_activate'
 /usr/share/rubygems/rubygems.rb:183:in `try_activate'

**Comment by avit** [comment]
The gem dependencies were changed here to block supporting newer versions (rspec 3.5 at the time):

https://github.com/NoRedInk/rspec-retry/commit/53363e2ab981f280609a95bcecbd6de4350203de#diff-374f3b14dbd20f435fcd320439b5887d

It might still be compatible with 3.7, if this just gets changed back to `~> 3.3`

**Comment by valscion** [comment]
Seems like this is resolved by #81 that has been merged?
