### ISSUE TITLE
Exponential Backoff

### ISSUE THREAD

**Issue by thedrow** [NoRedInk/rspec-retry#91]
Tests with intermediate network failures have a tendency to pass if an exponential random backoff is used.
Would you mind if we added it?

**Comment by patveith** [comment]
@thedrow I added a [pull request here](https://github.com/NoRedInk/rspec-retry/pull/94) if you'd like to take a look

**Comment by michaelglass** [comment]
We don't mind

**Comment by michaelglass** [comment]
released 0.6.0, thanks, you two!
